language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt

script:
    - flake8 .
    - pylint tokenizer.py tests/test_tokenizer.py
    - mypy .
    - python -m pytest tests/test_tokenizer.py --cov=tokenizer --cov-report=term

after_success:
    - codecov
